name: callkeep_example
description: Demonstrates how to use the callkeep plugin.
publish_to: 'none'

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_callkeep:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
